name: Create Repository without template

on:
  workflow_dispatch:
    inputs:
      repository_name:
        description: 'Enter the name of the new repository'
        required: true
      branches:
        description: 'Enter the names of the branches (comma-separated)'
        required: true

jobs:
  create_repository:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Repository 
        run: |
          REPO_NAME="${{ github.event.inputs.repository_name }}"
          BRANCHES="${{ github.event.inputs.branches }}"
          curl -X POST \
            -H "Authorization: token ${{ secrets.API_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/user/repos \
            -d '{"name": "'"$REPO_NAME"'","private":true}'
          
          IFS=',' read -ra BRANCH_LIST <<< "$BRANCHES"
          for branch in "${BRANCH_LIST[@]}"; do
            
            curl -X POST \
              -H "Authorization: token ${{ secrets.API_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              -d "{\"ref\": \"refs/heads/$branch\"}" \
              "https://api.github.com/repos/${{ github.repository }}/git/refs"
          done
      - name: Create README.md
        run: |
          echo "# $REPO_NAME" >> README.md
          git add README.md
          git commit -m "Add README.md"
          git push origin main
