on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
    - name: Build Module
      shell: pwsh
      run: |
        $repo_name = "test_repo_1"
        gh repo create $repo_name --private --template=https://github.com/ktyknk1999/CRUD.git --include-all-branches
        echo "exiting in 10 seconds"
        Start-Sleep -s 10




