on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
    - name: Build Module
      shell: pwsh
      run: |
        $repo_name = Read-Host "Please enter your new repo name"
        gh repo create $repo_name --private --template=CRUD --include-all-branches
        echo "exiting in 10 seconds"
        Start-Sleep -s 10




